"""make created_at nullable

Revision ID: 006671e5942e
Revises: 3968bdcaf3dd
Create Date: 2025-08-28 21:55:33.082352

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '006671e5942e'
down_revision = '3968bdcaf3dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('emailUser'))
        batch_op.drop_index(batch_op.f('nameUser'))

    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nameUser', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('emailUser', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('passwordUser', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('is_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('verification_code', mysql.VARCHAR(length=6), nullable=True),
    sa.Column('verification_code_expiration', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('nameUser'), ['nameUser'], unique=True)
        batch_op.create_index(batch_op.f('emailUser'), ['emailUser'], unique=True)

    # ### end Alembic commands ###
