"""Add dashboard tables

Revision ID: 3a168a450892
Revises: 006671e5942e
Create Date: 2025-09-06 19:13:40.711327

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3a168a450892'
down_revision = '006671e5942e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('emailUser'))
        batch_op.drop_index(batch_op.f('nameUser'))

    op.drop_table('users')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('orderDate',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('orderDate',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    op.create_table('users',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nameUser', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('emailUser', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('passwordUser', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('is_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('verification_code', mysql.VARCHAR(length=6), nullable=True),
    sa.Column('verification_code_expiration', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('nameUser'), ['nameUser'], unique=True)
        batch_op.create_index(batch_op.f('emailUser'), ['emailUser'], unique=True)

    # ### end Alembic commands ###
