"""Add admin field and roles

Revision ID: cbe63df01426
Revises: 
Create Date: 2025-08-27 20:18:02.646774

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cbe63df01426'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('emailUser'))

    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('idUser', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nameUser', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('emailUser', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('verification_code', mysql.VARCHAR(length=6), nullable=True),
    sa.Column('code_expiration', mysql.DATETIME(), nullable=True),
    sa.Column('is_verified', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('idUser'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('emailUser'), ['emailUser'], unique=True)

    # ### end Alembic commands ###
